### ISSUE TITLE
complete event doesn't work

### ISSUE THREAD

**Issue by equinusocio** [LottieFiles/lottie-react#10]
It seems that the `complete` event is not working/throw. Taking this example:

```jsx
import React from 'react';
import { Player } from '@lottiefiles/react-lottie-player';
 
class App extends React.Component {
  constructor(props) {
    super(props);
    this.player = React.createRef();
  }
 
  render() {
    return (
      <Player
        onEvent={event => {
          if (event === 'complete') console.log('Finished'); 
        }}
        ref={this.player}
        autoplay={false}
        loop={false}
        controls={true}
        src="https://assets3.lottiefiles.com/packages/lf20_XZ3pkn.json"
      ></Player>
    );
  }
}
 
export default App;
```
There isn't any `complete` event, but logging the `event`, I see only `load`, `play`, and `frame` events. 

Digging the code, it seems that no event is triggered inside the `complete` listener:
https://github.com/LottieFiles/lottie-react/blob/8564a38e0ea2b00a264f68ff8f5eac5da17bea68/src/Player.tsx#L252-L255

There should be a `this.triggerEvent(PlayerEvent.Complete);`

**Comment by ahrbil** [comment]
Hello @equinusocio
That is correct I'm having the same issue here, no COMPLETE event is fired
and on login the event there are only three events being fired which are the ones you mentioned.
did you find any workaround for this?

**Comment by ahrbil** [comment]
for anyone facing the same issue
you can get a reference to the player instance and then manually listen for any supported animation event.

```js
playerInstance.current?.state?.instance?.addEventListener("complete", () => {
    console.log("ANIMATION COMPLETED");
  });
```

**Comment by AlexisMunozC** [comment]
Hi, I have the same problem, but we use this:
```
class Test extends React.Component{
     constructor(props){
          super(props);
          this.state = {
               lottie: null
          }
     }
     componentDidMount(){
          lottie.addEventListener('complete', ()=>{
               //CODE ON COMPLETE
          })
     }
     render(){
          return(
               <Player lottieRef={(instance)= > {this.setState({lottie: instance}}}/>
          )
     }
}
```
