### ISSUE TITLE
Multiple Instances on the Same Page Has Wrapper ID Conflict

### ISSUE THREAD

**Issue by jonobr1** [LottieFiles/lottie-react#11]
I noticed that there is an ID attached to the `<div />` containing the SVG or Canvas. It's always `lottie` which breaks down if there are more than one instance of the player on a page. Is there a way to specify the id?

<img width="399" alt="Screen Shot 2020-11-24 at 4 49 09 PM" src="https://user-images.githubusercontent.com/220033/100155445-4a727b00-2e75-11eb-934e-8e7a40769288.png">

**Comment by karamalie** [comment]
Noted. Will look into a fix.
Thank you :)

**Comment by karamalie** [comment]
Adding the id as a prop option.

**Comment by jonobr1** [comment]
Amazing, thanks!

**Comment by Siignature** [comment]
Hello, it seems it still doesn't work properly. When multiple components in the same page, when you apply, for example, a speed for one of them, it applies to all lottie components in the page. Even when setting a different id for each component.

**Comment by samuelOsborne** [comment]
Hi @Siignature thanks for brining this to our attention. Will look in to it.

**Comment by samuelOsborne** [comment]
Hi @Siignature Have you updated your version of the player? I can't manage to reproduce this bug:

https://codesandbox.io/s/lottie-react-speed-test-veuux?file=/src/App.js

**Comment by Siignature** [comment]
I am using React 16, maybe is it the problem?

**Comment by samuelOsborne** [comment]
@Siignature I don't think so. Are you using the latest version of lottie-react?

**Comment by Siignature** [comment]
@samuelOsborne Yes, 3.4.1

**Comment by samuelOsborne** [comment]
@Siignature Could you share how you implemented it ?
