### ISSUE TITLE
setSeeker frame: number | string, or just number?

### ISSUE THREAD

**Issue by BrendanBerkley** [LottieFiles/lottie-react#111]
## Overview

Mismatch between readme and code. Readme says that setSeeker can accept a number or a string (to handle percents), but the code only allows a number. (Not sure which is intended to be correct!)

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by samuelOsborne** [comment]
Thanks @BrendanBerkley, should be a number.
