### ISSUE TITLE
`dotLottie` file support

### ISSUE THREAD

**Issue by aungbobotun** [LottieFiles/lottie-react#123]
When can we expect the `dotLottie` file support for this package?

**Comment by samuelOsborne** [comment]
Hi @aungbobotun, dotLottie wouldn't be supported within this package itself, but in a separate one. I'll re-ping this issue when it comes around!

Cheers

**Comment by gj-inoriega** [comment]
Any news about dotLottie support @samuelOsborne?

**Comment by samuelOsborne** [comment]
@gj-inoriega its available here https://www.npmjs.com/package/@dotlottie/react-player
