### ISSUE TITLE
Player has an extra <div> layer

### ISSUE THREAD

**Issue by peter-jerry-ye** [LottieFiles/lottie-react#14]
With this layer, the style is not applied to the actual 'Player'. Perhaps it should be `React.Fragment`?

[example](https://codesandbox.io/s/lottie-qnwsk)

**Comment by karamalie** [comment]
Will have a look @peter-jerry-ye . Thanks for the feedback

**Comment by samuelOsborne** [comment]
hi @peter-jerry-ye, to style the player, you can define your styling in the ".lf-player-container" class. This extra div is necessary to contain the controls.
