### ISSUE TITLE
Can I set the Color for the Animation

### ISSUE THREAD

**Issue by ANDRUXUIS** [LottieFiles/lottie-react#17]
It would be a lot cooler if we can change the color of the animation 

is there any method to achieve this

**Comment by AlexisMunozC** [comment]
Hi, you can add classes from after effects, just rename the layers by adding a dot (.) at start, then you can change the color using css by adding:
.my_class, .myclass *{
stroke: red;
fill: red;
}

**Comment by ANDRUXUIS** [comment]
Can you walk me through the process,  because I have never used after affect

**Comment by samuelOsborne** [comment]
Hi @ANDRUXUIS, @AlexisMunozC is referring to this technique: https://www.youtube.com/watch?v=gfoImTlEcIU

**Comment by ANDRUXUIS** [comment]
@samuelOsborne thank you
