### ISSUE TITLE
Toggle is not working

### ISSUE THREAD

**Issue by eleviven** [LottieFiles/lottie-react#26]
i can't found how can i do toggle. I tried that way but not working.

```js
export default function Home() {
  const ref = createRef();
  const [isSelected, setIsSelected] = useState(false);

  const handleClick = () => {
    if (isSelected) {
      ref.current.play(0, 30);
    } else {
      ref.current.play(30, 0);
    }
    setIsSelected(!isSelected);
  };

  return (
    <div>
      <button onClick={handleClick}>
        <Player
          ref={ref}
          src="/lottie/star.json"
          style={{ height: "40px", width: "40px" }}
        />
      </button>
    </div>
  );
}
```

**Comment by karamalie** [comment]
hi @eleviven 
Do you want to play from frame 0 to 30 if isSelected. if not reverse from 30 to 0?

**Comment by eleviven** [comment]
> hi @eleviven
> Do you want to play from frame 0 to 30 if isSelected. if not reverse from 30 to 0?

I want to play from 0 to 30 and stop it.

**Comment by GabrielDeM** [comment]
Hello @eleviven,

You can use `playSegments([0, 30], true)` and then `playSegments([30, 0], true)`.

If you want to stop at last frame, add `keepLastFrame={true}` on your Player component. It has been added a few days ago so you may need to update the library version.

**Comment by eleviven** [comment]
@GabrielDeM Thank you for reply
