### ISSUE TITLE
How to customize the progress color of control bar?

### ISSUE THREAD

**Issue by uncleLian** [LottieFiles/lottie-react#27]
background-image: -webkit-gradient(linear, 0% 0%, 100% 0%, color-stop(0.315789, rgba(15, 204, 206, 0.4)), color-stop(0.315789, rgb(218, 225, 231)));

How to change？

**Comment by samuelOsborne** [comment]
@uncleLian The progress bar has the '.lf-progress' class, which you can override. You can also get the element by its Id: 'track', and apply styling to it this way.
