### ISSUE TITLE
Support for React 17?

### ISSUE THREAD

**Issue by bumTomica** [LottieFiles/lottie-react#31]
```
Found: react@17.0.1
node_modules/react
react@"^17.0.1" from the root project

Could not resolve dependency:
peer react@"^16.8.6" from @lottiefiles/react-lottie-player@3.0.0
node_modules/@lottiefiles/react-lottie-player
@lottiefiles/react-lottie-player@"^3.0.0" from the root project
```

**Comment by SweetSoul** [comment]
Same here... there are some other community maintained repos which accept React 17 and the official don't 🤦‍♂️ 
Eg.: https://github.com/mifi/react-lottie-player

**Comment by gnowland** [comment]
`npm install --save @lottiefiles/react-lottie-player --legacy-peer-deps` yolo

**Comment by karamalie** [comment]
Upgraded to react 17 on latest version
