### ISSUE TITLE
Can't get latest version with rendererSettings prop

### ISSUE THREAD

**Issue by ajbater** [LottieFiles/lottie-react#32]
Hey, I'm trying to use the latest version of this, 3.0.1 so that I can use the new `rendererSettings` prop. Unfortunately I get the error `No matching version found for @lottiefiles/react-lottie-player@3.0.1.` - any idea why this would be?

**Comment by karamalie** [comment]
Pushed up to npm. Do have a check and get back to us ^^ 

Thank you

**Comment by ajbater** [comment]
All good now, thanks again!

**Comment by karamalie** [comment]
you re welcome! closing this issue & happy coding :)
