### ISSUE TITLE
Inputs (eg. text, checkbox) lose their browser default focus styling

### ISSUE THREAD

**Issue by cjulian** [LottieFiles/lottie-react#38]
If I import the player onto a page with inputs, the default blue outline that Chrome adds when focusing on an input element no longer appears.

```javascript
import { Player } from "@lottiefiles/react-lottie-player";
export default () => <input type='text'/>
```

In the above example their will be no outline on focus.  If you comment out the import the focus outline will return.

It appears to be caused by this CSS with a very generic selector:
https://github.com/LottieFiles/lottie-react/blob/master/src/Styles.css#L74

**Comment by hs-cjulian** [comment]
It appears to be caused by this line of CSS: https://github.com/LottieFiles/lottie-react/blob/master/src/Styles.css#L74

**Comment by karamalie** [comment]
Noted. Will update the css for next version bump

**Comment by cjulian** [comment]
> Noted. Will update the css for next version bump

Thank you so much.

**Comment by karamalie** [comment]
Issue should be fixed now. focus outline will only be set within the Lottie container
