### ISSUE TITLE
Doesn't play some lottiefiles

### ISSUE THREAD

**Issue by ThewBear** [LottieFiles/lottie-react#41]
This file https://lottiefiles.com/48503-orange-bubble is not animating when using `@lottiefiles/react-lottie-player`.

**Comment by karamalie** [comment]
Try with the latest version of the player. It should work with v 3.1.1

**Comment by ThewBear** [comment]
Still doesn't play. I created a codesandbox with comparison to `react-lottie`
https://codesandbox.io/s/react-lottie-player-41-k0c0i

**Comment by karamalie** [comment]
It seems the latest version of lottie-web engine broke a few things for some effects. The https://www.npmjs.com/package/@lottiefiles/lottie-player version 0.5.1 plays this animation whearas the new versions dont. This repo is a wrapper around the lottie web engine, Theres no fixes we can push for now.

**Comment by sohil8chhabriya** [comment]
@karamalie, I dont see even on 0.5.1 it is working. Could you please see if anything is missed?

**Comment by karamalie** [comment]
@sohil8chhabriya  alright I ll have another go at it

**Comment by karamalie** [comment]
pushed out an update @sohil8chhabriya @ThewBear . That should fix it. v3.0.3, do drop me an update if everythings okay

**Comment by ThewBear** [comment]
I confirm that `v3.1.3` solve this issue.

**Comment by sohil8chhabriya** [comment]
Yes. `v3.1.3` fixes the issue, Looks like github pipeline fails for some reason. Thank you so much @karamalie

**Comment by karamalie** [comment]
brilliant! you re welcome guys. happy coding. i ll work on fixing the pipeline next week :) 
closing this issue
