### ISSUE TITLE
Why is renderer="canvas" not working ?

### ISSUE THREAD

**Issue by anilsoniaurionpro** [LottieFiles/lottie-react#59]
## Overview
renderer = "svg" or "html" is working but renderer = "canvas" isn't working
...

**Comment by anilsoniaurionpro** [comment]
Update:
The JSON URL used in the Readme works with HTML and SVG renderer.

If I use a different file, canvas renderer works .

**Comment by VidyBack** [comment]
I realized some AE features arent supported in the canvas renderer

**Comment by anilsoniaurionpro** [comment]
I realized the same AE features arent supported in canvas renderer.
