### ISSUE TITLE
Component pollutes global styles

### ISSUE THREAD

**Issue by gregbacchus** [LottieFiles/lottie-react#7]
Using the player in my site, I noticed that it pollutes the styles of the whole page. E.g. it set's styles for `.btn`, setting the width to `14px` so now all buttons on my site want to be only 14px wide.

**Comment by karamalie** [comment]
will go through the entire code and address this

**Comment by karamalie** [comment]
Prefixed the class name for a quick fix. The update was pushed out earlier. Closing this issue :) 
Thanks for your feedback @gregbacchus
