### ISSUE TITLE
Speed is overriden

### ISSUE THREAD

**Issue by leobenkel** [LottieFiles/lottie-react#72]
**Tell us about your environment**
* **Browser and Browser Version:**
chrome 98

**What did you do? Please explain the steps you took before you encountered the problem.**

I have more than one lottie icon on a given page. it seems that the last one to load is setting the `speed` for all of them. I have one with `speed="0.5"` and 2 with a `speed="2"` and it seems that all of them behave at a speed of 2.

**What did you expect to happen?**

I would expect each lottie component to be independent. 

_I tried to edit the `labels` but i don't think i have the rights to do it._

**Comment by leobenkel** [comment]
at https://github.com/LottieFiles/lottie-react/blob/1934ce4f9cc8fb74f8c9e64765ab6e08464d239a/src/Player.tsx#L304

Shouldn't it be `newInstance.setSpeed` ?

**Comment by samuelOsborne** [comment]
Hi @leobenkel, I haven't managed to reproduce this error, are you using the latest version? Heres my codesandbox:

https://codesandbox.io/s/lottie-react-speed-test-veuux?file=/src/App.js

**Comment by leobenkel** [comment]
look at this one https://codesandbox.io/s/lottie-react-speed-test-forked-g1xzur?file=/src/App.js

**Comment by leobenkel** [comment]
cool thanks ! :)

**Comment by samuelOsborne** [comment]
Thanks @leobenkel this should be fixed in 3.4.2 :)

**Comment by leobenkel** [comment]
it works ! Thanks !
