### ISSUE TITLE
Support for React 16.8.0+ ?

### ISSUE THREAD

**Issue by sosamuel** [LottieFiles/lottie-react#77]
```
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.13.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from @lottiefiles/react-lottie-player@3.4.2
npm ERR! node_modules/@lottiefiles/react-lottie-player
npm ERR!   @lottiefiles/react-lottie-player@"*" from the root project
```

**Comment by samuelOsborne** [comment]
Hi @sosamuel I can't reproduce this error locally or on code sand box. Could you possible share your package.json file ?

https://codesandbox.io/s/flamboyant-shamir-wzjqpq?file=/package.json

**Comment by krotovic** [comment]
I may have found similar issue... I have in dependencies `react@^17.0.2` and `@lottiefiles/react-lottie-player@"^3.4.2` but `npm install --no-lockfile` crashes with
```
npm ERR! While resolving: web_v2@6.1.0
npm ERR! Found: @lottiefiles/react-lottie-player@3.1.2
npm ERR! node_modules/@lottiefiles/react-lottie-player
npm ERR!   @lottiefiles/react-lottie-player@"^3.4.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @lottiefiles/react-lottie-player@"^3.4.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2" from @lottiefiles/react-lottie-player@3.4.2
npm ERR!   node_modules/@lottiefiles/react-lottie-player
npm ERR!     @lottiefiles/react-lottie-player@"^3.4.2" from the root project
npm ERR! 
```

I'm not sure whose issue it is, npm or yours.

**Comment by RonaldDBezerra** [comment]
hello friend, I have the same problem with my lottie, it doesn't work for version 18.0.0 of react. Does anyone know if there is an update that fixes this?

**Comment by samuelOsborne** [comment]
Hey everyone, please try out version v3.4.5

https://www.npmjs.com/package/@lottiefiles/react-lottie-player/v/3.4.5

**Comment by ANIRUDHADITHYA** [comment]
animation loads and display twice in react 18

**Comment by samuelOsborne** [comment]
@ANIRUDHADITHYA I can't reproduce this issue

https://codesandbox.io/s/react-18-lottie-player-uegtql

**Comment by ANIRUDHADITHYA** [comment]
@samuelOsborne I have made there kindly check https://codesandbox.io/s/react-18-lottie-player-uegtql

in style using width 100% make the component double

**Comment by samuelOsborne** [comment]
@ANIRUDHADITHYA You need to send my the link to your forked codesandbox.

I put width 100% on mine and couldn't reproduce:
https://codesandbox.io/s/react-18-lottie-player-uegtql?file=/src/App.js
