### ISSUE TITLE
[Feature request] keepLastFrame

### ISSUE THREAD

**Issue by equinusocio** [LottieFiles/lottie-react#9]
Hello, I don't know if this is already possible using other API's (if yes, can you show me how?), but I would suggest 2 solutions

## 1 New `keepLastFrame` property

When the animation is not looping (`loop={false}`), when `keepLastFrame` property is `true`, the player should keep the last animation frame. This is particularly useful when playing entrance animations and the elements should stay in their final position when the animation ends.

https://github.com/LottieFiles/lottie-react/blob/8564a38e0ea2b00a264f68ff8f5eac5da17bea68/src/Player.tsx#L252-L255

This can become:

```js
newInstance.addEventListener('complete', () => {
     this.setState({ playerState: PlayerState.Paused });
     (!loop & keepLastFrame) ? this.setSeeker(0) : this.setSeeker(100);  // Dunno the real number here
});
```

---

## 2 Prevent frames reset

If you don't want to make this optional, I would suggest removing `this.setSeeker(0)` and prevent the frames reset (like the standard HTML player)

**Comment by keriat** [comment]
Vote for it too.

**Comment by amrosama2020** [comment]
Voting too, I'm using this as a workaround for now

```JavaScript
<Player
          autoplay
          ref={animationRef}
          src="/images/check-animation.json"
          style={{ height: '200px', width: '200px' }}
          onEvent={event => {
            if (event === 'complete') {
              window.setTimeout(() => animationRef.current.setSeeker(animationRef.current.state.instance.totalFrames))
            }
          }}
      />
```
