### ISSUE TITLE
react 18 and strict mode duplicates animation

### ISSUE THREAD

**Issue by fnavarrodev** [LottieFiles/lottie-react#92]
## Overview

We updated to react 18 and we have strict mode enabled and we noticed that in development mode our animations appear duplicated. 

## Consuming repo

https://github.com/LottieFiles/lottie-react v3.4.5

**Comment by samuelOsborne** [comment]
@fnavarrodev Im having trouble replicating this issue, could you give more info on your set up please?

https://codesandbox.io/s/react-18-lottie-player-uegtql?file=/src/App.js

**Comment by fnavarrodev** [comment]
Hi, without the style attribute is happening

https://codesandbox.io/s/react-18-lottie-player-forked-slq27n

In my case in a next.js project disabling "react strict mode" fixes the issue

**Comment by samuelOsborne** [comment]
@fnavarrodev thanks, looking in to this

**Comment by theashraf** [comment]
Hi @fnavarrodev 
The issue has been fixed in version `3.4.7`
https://codesandbox.io/s/react-18-lottie-player-forked-8n2ybt
Thanks

**Comment by fnavarrodev** [comment]
Hi @theashraf Awesome. Thanks a lot 🚀
