### ISSUE TITLE
Slow loading 

### ISSUE THREAD

**Issue by masudhossain** [LottieFiles/lottie-react#99]
## Overview
I've noticed that the loading speed of the animations is very slow, which i assume is because of the .json endpoint. Is it possible to download the .json and use it within our project so it loads instantly?

## Consuming repo

> What repo were you working in when this issue occurred?
lottie-react
...

## Labels

- [Bug ] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
Hi @masudhossain, 
the `src` prop accepts animationData object as well, so you can easily download your lottie animations and just pass the animationData object to the src prop of `<Player />`. kindly check this example  https://codesandbox.io/s/lottie-static-asset-110q8q

**Comment by masudhossain** [comment]
Amazing, thanks @theashraf
